const text = [
  "jelly sit amet consectetur adipisicing elit. Nobis labore laborum officia, cumque sed placeat totam consectetur aut recusandae architecto aperiam, omnis doloremque, quae ex beatae cupiditate neque accusantium ipsam? Numquam impedit, consequatur maxime laboriosam quo ex iure in quod porro voluptatibus optio beatae ratione vitae enim voluptatem quia blanditiis odit earum nisi dignissimos provident. Quasi enim iure voluptates placeat? Iure pariatur illo commodi voluptatibus repudiandae accusamus nihil, optio vel laborum nostrum a ut necessitatibus saepe nesciunt labore earum repellat atque quos temporibus eaque nemo ducimus maxime incidunt perferendis! Minus. Voluptates iusto itaque expedita, labore beatae, tempore officiis ipsum eveniet praesentium iure possimus hic, nam distinctio minus explicabo nisi quisquam. Distinctio tempore commodi officiis odio beatae rem non sapiente cupiditate. Consectetur delectus consequatur similique ipsum ratione blanditiis, aspernatur nisi numquam distinctio magnam quia voluptatibus illum quasi veniam ut non, sit harum dolorum velit! Nam voluptatibus reprehenderit autem! Explicabo, recusandae amet",

  "next level color, sit amet consectetur adipisicing elit. Voluptatem assumenda officiis nisi temporibus in id placeat. e quidem nobis, nam quisquam asperiores id sunt. Vel, quos. Consectetur error iste beatae eos vel hic fugiatRatione blanditiis temporibus doloremque porro beatae odio, dolores autem officiis non, quas delectus et.Quas dignissimos tenetur dicta velit! Error adipisci ratione minus facere, illo consectetur eius neque soluta tempore velit, sunt maiores laborum eveniet repudiandae dolores aliquam odio? Hic sapiente necessitatibus expedita vel?Accusantium officia voluptatum a magnam expedita veniam eveniet consequatur, cum eaque magni beata. ",

  "zombie sfkh[oidrthei.Quas dignissimos tenetur dicta velit! Error adipisci ratione minus facere, illo consectetur eius neque soluta tempore velit, sunt maiores laborum eveniet repudiandae dolores aliquam odio? Hic sapiente necessitatibus expedita vel?Accusantium officia voluptatum a magnam expedita veniam eveniet consequatur, cum eaque magni beata.",

  " Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem nobis doloribus delectus impedit quaerat vitae perspiciatis, nostrum repellendus quod obcaecati maiores minima numquam voluptatem sequi, maxime alias officia nihil ea.  Nesciunt quibusdam voluptatum corrupti commodi animi a eligendi, aliquid consequatur maxime provident reprehenderit modi nulla, nisi cum esse eos ipsam, ducimus voluptatibus sint voluptas. Accusantium inventore animi laborum assumenda quia. ",

  " Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem nobis doloribus delectus impedit quaerat vitae perspiciatis, nostrum repellendus quod obcaecati maiores minima numquam voluptatem sequi, maxime alias officia nihil ea.  Nesciunt quibusdam voluptatum corrupti commodi animi a eligendi, aliquid consequatur maxime provident reprehenderit modi nulla, nisi cum esse eos ipsam, ducimus voluptatibus sint voluptas. Accusantium inventore animi laborum assumenda quia",

  " Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem nobis doloribus delectus impedit quaerat vitae perspiciatis, nostrum repellendus quod obcaecati maiores minima numquam voluptatem sequi, maxime alias officia nihil ea.  Nesciunt quibusdam voluptatum corrupti commodi animi a eligendi, aliquid consequatur maxime provident reprehenderit modi nulla, nisi cum esse eos ipsam, ducimus voluptatibus sint voluptas. Accusantium inventore animi laborum assumenda quia",

  " Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem nobis doloribus delectus impedit quaerat vitae perspiciatis, nostrum repellendus quod obcaecati maiores minima numquam voluptatem sequi, maxime alias officia nihil ea.  Nesciunt quibusdam voluptatum corrupti commodi animi a eligendi, aliquid consequatur maxime provident reprehenderit modi nulla, nisi cum esse eos ipsam, ducimus voluptatibus sint voluptas. Accusantium inventore animi laborum assumenda quia",

  " Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem nobis doloribus delectus impedit quaerat vitae perspiciatis, nostrum repellendus quod obcaecati maiores minima numquam voluptatem sequi, maxime alias officia nihil ea.  Nesciunt quibusdam voluptatum corrupti commodi animi a eligendi, aliquid consequatur maxime provident reprehenderit modi nulla, nisi cum esse eos ipsam, ducimus voluptatibus sint voluptas. Accusantium inventore animi laborum assumenda quia",

  " Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem nobis doloribus delectus impedit quaerat vitae perspiciatis, nostrum repellendus quod obcaecati maiores minima numquam voluptatem sequi, maxime alias officia nihil ea.  Nesciunt quibusdam voluptatum corrupti commodi animi a eligendi, aliquid consequatur maxime provident reprehenderit modi nulla, nisi cum esse eos ipsam, ducimus voluptatibus sint voluptas. Accusantium inventore animi laborum assumenda quia",
  
  " Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem nobis doloribus delectus impedit quaerat vitae perspiciatis, nostrum repellendus quod obcaecati maiores minima numquam voluptatem sequi, maxime alias officia nihil ea.  Nesciunt quibusdam voluptatum corrupti commodi animi a eligendi, aliquid consequatur maxime provident reprehenderit modi nulla, nisi cum esse eos ipsam, ducimus voluptatibus sint voluptas. Accusantium inventore animi laborum assumenda quia",
];
export default text;
